http:
  addr: ":8080"

auth:
  secret: "secret"

log:
  level: "debug"

postgres:
  connect: "postgres://admin:123456789@postgres:5432/gotubedb?sslmode=disable"

mongo:
  connect: "mongodb://admin:123456789@mongo:27017"

s3:
  addr: "s3:9000"
  access_key: "admin"
  secret_key: "123456789"

redis:
  connect: "redis://redis:6379"
