version: "3.9"

services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .stage.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .postgres.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  pg_data:
