# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: run-infra
      - task: run-app-prod

  run-infra:
    cmds:
      - docker compose -p gotube-infra -f ./infra/docker-compose.yaml up --build -d

  stop-infra:
    cmds:
      - docker compose -p gotube-infra -f ./infra/docker-compose.yaml down

  run-app-debug:
    cmds:
      - cmd: go run ./cmd/api-server -conf configs/app.debug.env
        ignore_error: true

  run-app-prod:
    cmds:
      - docker compose -p gotube-app-prod -f docker-compose.yaml up --build -d

  stop-app-prod:
    cmds:
      - docker compose -p gotube-app-prod -f docker-compose.yaml down

  run-web-dev:
    cmds:
      - echo "Hello, world!"

  run-web-prod:
    cmds:
      - echo "Hello, world!"

  stop-web-prod:
    cmds:
      - echo "Hello, world!"

  migrate:
    env:
      ACTION: up
      DATABASE:
    cmds:
      - go run ./cmd/migrator -action $ACTION -database $DATABASE {{.CLI_ARGS}}
