# https://taskfile.dev

version: '3'

vars:
  PROJECT: gotube

tasks:
  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy

  audit:
    cmds:
      - go mod verify
      - go vet ./...
      - golangci-lint run ./...
      - govulncheck ./...
      - go test -race -buildvcs -vet=off ./...

  test:
    cmds:
      - go test -v -race -buildvcs ./...

  test/cover:
    cmds:
      - go test -v -race -buildvcs -coverprofile=/tmp/coverage.out ./... 
      - go tool cover -html=/tmp/coverage.out

  ci:
    cmds:
      - task: tidy
      - task: audit
      - task: test

  build/local:
    cmds:
      - go build -o -v /tmp/{{.PROJECT}}/api-server ./cmd/api-server

  run/local:
    deps: [build/local]
    cmds:
      - /tmp/{{.PROJECT}}/api-server -conf .local.env

  run/docker:
    deps: [ci]
    cmds:
      - docker compose up --build -d

  stop/docker:
    cmds:
      - docker compose down

  migrate/new:
    cmds:
      - migrate create -ext sql -dir ./assets/migrations -seq {{.name}}

  migrate/up:
    cmds:
      - migrate -path ./assets/migrations -database "postgres://{{.db_dsn}}" up
  
  migrate/down:
    cmds:
      - migrate -path ./assets/migrations -database "postgres://{{.db_dsn}}" down

  migrate/goto:
    cmds:
      - migrate -path ./assets/migrations -database "postgres://{{.db_dsn}}" goto {{.version}}

  migrate/force:
    cmds:
      - migrate -path ./assets/migrations -database "postgres://{{.db_dsn}}" force {{.version}}

  migrate/version:
    cmds:
      - migrate -path ./assets/migrations -database "postgres://{{.db_dsn}}" version