http:
  addr: ":8080"

auth:
  secret: "secret"

log:
  level: "debug"

postgres:
  connect: "postgres://admin:123456789@localhost:5432/gotubedb?sslmode=disable"

s3:
  addr: "localhost:9000"
  access_key: "admin"
  secret_key: "123456789"

redis:
  connect: "redis://localhost:6379"
